// Generated by CoffeeScript 1.6.2
$(function() {
  var Blog, blog, blogContainer$;

  blogContainer$ = $('#blog-container');
  Blog = (function() {
    function Blog(container, currentPage) {
      if (currentPage == null) {
        currentPage = 'http://lju.me/blog/_site/';
      }
      this.container$ = $(container);
      this.currentPage = currentPage;
    }

    Blog.prototype.updatePage = function(page) {
      var _this = this;

      return $.ajax(this.currentPage = page, {
        complete: function(data) {
          _this.container$.html(data.responseText);
          return _this.fixLinks();
        }
      });
    };

    Blog.prototype.fixLinks = function() {
      return $('#blog-container a[href*="blog/_site"]').on('click', function(e) {
        e.preventDefault();
        e.stopPropagation();
        return blog.updatePage(this.href);
      }).mousedown(function(e) {
        e.preventDefault();
        return e.stopPropagation();
      });
    };

    return Blog;

  })();
  blog = new Blog(document.getElementById('blog-container'));
  return blog.fixLinks();
  /*
  # Make an ajax call and get the new page content
  # After getting it, clear out the current page,
  # and replace with the new html.
  bootstrap = () ->
    loadNewPage = (e) ->
      swapData = (data) ->
        blogContainer$.html(data.responseText)
        do fixLinks
  
      page = this.currentPage
      options = {complete: swapData}
      $.ajax(page, options)
  
    blogContainer$.on('pageChange', loadNewPage)
  
  fixLinks = () ->
    $('#blog-container a[href*="blog/_site"]').on('mousedown', (e) ->
      e.preventDefault()
      e.stopPropagation()
      blog.updatePage(this.href)
      return null
    )
  */

});
